### ISSUE TITLE
설치는 어떻게 하는지 알려주세요

### ISSUE THREAD

**Issue by whoansoo** [whatyoulove/fastblog#1]
아직 초보라서 설치는 어떻게 하는지 알려주세요
프로젝트 생성 후에 migrate 하니깐..에러가 나서..
진도를 나갈수가 없네요. 번거로우시겠지만
빠른 답변 부탁드립니다.

whoansoo@testsvr:~/work/tistory$ python3 manage.py runserver
t!i*@4v!nk_ukhg*(ktdkt2&u1)m2v*ri!xj&#tqws(^+*m(9#
t!i*@4v!nk_ukhg*(ktdkt2&u1)m2v*ri!xj&#tqws(^+*m(9#
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/whoansoo/.local/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/whoansoo/.local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/whoansoo/.local/lib/python3.6/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/whoansoo/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/whoansoo/.local/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/whoansoo/.local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/whoansoo/.local/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/whoansoo/.local/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_social_share'

**Comment by aciddust** [comment]
**ModuleNotFoundError: No module named 'django_social_share'**

`python manage.py 0.0.0.0:8080` 과 같이 시작하면  
장고 프로젝트에서 import 하여 사용중인 `django_social_share` 패키지를 찾을텐데  
없다고 알려주는 내용의 오류입니다.

아마 저거 외에도 몇가지 패키지가 더 필요할겁니다.

```bash
pip install django_social_share
pip install django-taggit
pip install pillow
```

패키지 설치 이후  
```bash
python manage.py makemigrations blogs helpers users
python manage.py migrate
python manage.py 0.0.0.0:8080
```
